// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBA_Manager_Api.DataAccess;

namespace NBA_Manager_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211126174027_RemovedUnnecessaryIdVariables")]
    partial class RemovedUnnecessaryIdVariables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NBA_Manager_Api.Models.AuctionDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuctionModelId")
                        .HasColumnType("int");

                    b.Property<float>("Bid")
                        .HasColumnType("real");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("UsersPlayerModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuctionModelId");

                    b.HasIndex("UsersPlayerModelId");

                    b.ToTable("AuctionDetails");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.AuctionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Club")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Condition")
                        .HasColumnType("real");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("League")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.PlayerInfoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Club")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsLegend")
                        .HasColumnType("bit");

                    b.Property<string>("League")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PlayerInfos");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.PlayerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerInfoModelId")
                        .HasColumnType("int");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PlayerInfoModelId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.SponsorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("MatchPrize")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TitlePrize")
                        .HasColumnType("real");

                    b.Property<float>("WinPrize")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.SportsHallModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("IncomePerViewer")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("SeatsCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SportsHalls");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClubName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Money")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RankPoints")
                        .HasColumnType("int");

                    b.Property<int?>("SponsorModelId")
                        .HasColumnType("int");

                    b.Property<int?>("SportsHallModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SponsorModelId");

                    b.HasIndex("SportsHallModelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.UsersItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("ItemModelId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ItemModelId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersItems");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.UsersPlayerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Condition")
                        .HasColumnType("real");

                    b.Property<int>("Contract")
                        .HasColumnType("int");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnAuction")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerModelId")
                        .HasColumnType("int");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerModelId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersPlayers");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.AuctionDetailsModel", b =>
                {
                    b.HasOne("NBA_Manager_Api.Models.AuctionModel", "AuctionModel")
                        .WithMany("AuctionDetails")
                        .HasForeignKey("AuctionModelId");

                    b.HasOne("NBA_Manager_Api.Models.UsersPlayerModel", "UsersPlayerModel")
                        .WithMany("AuctionDetails")
                        .HasForeignKey("UsersPlayerModelId");

                    b.Navigation("AuctionModel");

                    b.Navigation("UsersPlayerModel");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.PlayerModel", b =>
                {
                    b.HasOne("NBA_Manager_Api.Models.PlayerInfoModel", "PlayerInfoModel")
                        .WithMany("PlayerModels")
                        .HasForeignKey("PlayerInfoModelId");

                    b.Navigation("PlayerInfoModel");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.UserModel", b =>
                {
                    b.HasOne("NBA_Manager_Api.Models.SponsorModel", "SponsorModel")
                        .WithMany("UserModels")
                        .HasForeignKey("SponsorModelId");

                    b.HasOne("NBA_Manager_Api.Models.SportsHallModel", "SportsHallModel")
                        .WithMany("UserModels")
                        .HasForeignKey("SportsHallModelId");

                    b.Navigation("SponsorModel");

                    b.Navigation("SportsHallModel");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.UsersItemModel", b =>
                {
                    b.HasOne("NBA_Manager_Api.Models.ItemModel", "ItemModel")
                        .WithMany("UsersItems")
                        .HasForeignKey("ItemModelId");

                    b.HasOne("NBA_Manager_Api.Models.UserModel", "UserModel")
                        .WithMany("UsersItems")
                        .HasForeignKey("UserId");

                    b.Navigation("ItemModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.UsersPlayerModel", b =>
                {
                    b.HasOne("NBA_Manager_Api.Models.PlayerModel", null)
                        .WithMany("UsersPlayers")
                        .HasForeignKey("PlayerModelId");

                    b.HasOne("NBA_Manager_Api.Models.UserModel", "UserModel")
                        .WithMany("UsersPlayers")
                        .HasForeignKey("UserId");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.AuctionModel", b =>
                {
                    b.Navigation("AuctionDetails");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.ItemModel", b =>
                {
                    b.Navigation("UsersItems");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.PlayerInfoModel", b =>
                {
                    b.Navigation("PlayerModels");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.PlayerModel", b =>
                {
                    b.Navigation("UsersPlayers");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.SponsorModel", b =>
                {
                    b.Navigation("UserModels");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.SportsHallModel", b =>
                {
                    b.Navigation("UserModels");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.UserModel", b =>
                {
                    b.Navigation("UsersItems");

                    b.Navigation("UsersPlayers");
                });

            modelBuilder.Entity("NBA_Manager_Api.Models.UsersPlayerModel", b =>
                {
                    b.Navigation("AuctionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
